### ISSUE TITLE
Build fails with NoClassDefFoundError: com/moowork/gradle/node/NodePlugin

### ISSUE THREAD

**Issue by sirianni** [srs/gradle-grunt-plugin#33]
I upgraded to '0.12' and received this error:
```
$ gradle --stacktrace clean build
Starting Build
FAILURE: Build failed with an exception.

* What went wrong:
com/moowork/gradle/node/NodePlugin
> com.moowork.gradle.node.NodePlugin

* Exception is:
java.lang.NoClassDefFoundError: com/moowork/gradle/node/NodePlugin
	at com.moowork.gradle.grunt.GruntPlugin.apply(GruntPlugin.groovy:16)
	at com.moowork.gradle.grunt.GruntPlugin.apply(GruntPlugin.groovy)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
	at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
	... 54 more
```

I do not get this error when using 0.11.  Here is my `build.gradle`:
```
plugins {
    id 'com.moowork.grunt' version '0.12'
}

node {
    version = '4.4.2'
    download = true
}
```

**Comment by srs** [comment]
I cannot seem to replicate this error. But you could try to apply the node plugin too, like this:

```
plugins {
  id 'com.moowork.node' version '0.12'
  id 'com.moowork.grunt' version '0.12'
}
```
